services:
  db_ecommerce:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ecommerce_network

  backend_ecommerce:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db_ecommerce
      - DB_PORT=5432
      - DEBUG=1
    depends_on:
      - db_ecommerce
    networks:
      - ecommerce_network

  frontend_ecommerce:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    command: "npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend_ecommerce
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
